name: ranking-app
services:
  web:
    build: .
    ports:
      - "8080:10000"
    volumes:
      - ./uploads:/app/uploads
    restart: always
    networks:
      - app-network
    environment:
      - PYTHONUNBUFFERED=1
      - FLASK_ENV=production
      - TIMEOUT=300

networks:
  app-network:
    driver: bridge 