name: ranking-app
services:
  web:
    build: .
    ports:
      - "${PORT:-10000}:${PORT:-10000}"
    volumes:
      - ./uploads:/app/uploads
    restart: always
    networks:
      - app-network
    environment:
      - PORT=${PORT:-10000}
      - PYTHONUNBUFFERED=1
      - FLASK_ENV=production

networks:
  app-network:
    driver: bridge 