name: ranking-app
services:
  web:
    build: .
    ports:
      - "8080:5000"
    volumes:
      - ./uploads:/app/uploads
    restart: always
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4G
        reservations:
          cpus: '1.0'
          memory: 2G 